### ISSUE TITLE
Please submit asterisk.patch upstream

### ISSUE THREAD

**Issue by coreyfarrell** [traud/asterisk-opus#12]
Hi @traud would you mind submitting asterisk.patch to gerrit?  We talked about it on IRC, the configure script already checks for opus and since Asterisk itself won't link to opusfile it should be fine.

My goal is to remove this need for non-developers to run ./bootstrap.sh.  I don't actually use opus (might in the future), this request is in response to a post on [asterisk-dev](http://lists.digium.com/pipermail/asterisk-dev/2017-November/076588.html) mailing list.

**Comment by traud** [comment]
See the [origin of that code…](http://github.com/asterisk/asterisk/commit/40aa28131bc30b4516da2b20eb1a1e043920169c#diff-67e997bcfdac55191033d57a16d1408a) it got removed because of [ASTERISK-26426](http://issues.asterisk.org/jira/browse/ASTERISK-26426).
Therefore, please, feel free to add that part back yourself.

**Comment by coreyfarrell** [comment]
Thanks for pointing me to the origin of the patch, I just got it merged.  I'm unsure when you want to update your README.md but starting with Asterisk 13.19.0 and 15.2.0 'asterisk.patch' will no longer be needed and your users will not need to run ./bootstrap.sh.
