### ISSUE TITLE
Issue with changing the opus packetization time to 60ms

### ISSUE THREAD

**Issue by mohit-dhiman** [traud/asterisk-opus#19]
Hi,
By default when I use the Opus codec the Packetization time of the RTP packets is 20 ms and If I try to change this time from 20 to 60 ms by adding the `allow=opus:60` entry in the Asterisk's sip.conf then the SDP is getting updated but the actual RTP packets are still transmitting at 20 ms interval.
Also, the timestamp isn't getting updated from 960 (48 * 20) to 2880 (48 * 60).

so would you be able to tell me how can this be resolved?

**Comment by traud** [comment]
Thank you for reporting. This issue is mentioned in MISSING. However, it is missing here because it is [missing in Asterisk …](https://issues.asterisk.org/jira/browse/ASTERISK-25579) When that Asterisk issue is resolved or you find another way to resolve it, packetization support can be added/double-checked here in this module. In that case, please, re-open this issue here.

**Comment by mohit-dhiman** [comment]
I have gone through the Asterisk issue and what I understood is that Asterisk only applies the packetization conf to the smooth codecs.
So, If I restrict the opus codec to run in a constant bitrate mode will that be enough for it to qualify as the smooth codec and what would be `minimum_bytes` and the calculation of `get_length` of the opus `ast_codec`.

**Comment by traud** [comment]
That is an interesting question, I do not know the answer for. Because this is a general Opus Codec question, I recommend to consult [their mailing list …](https://opus-codec.org/contact/)

**Comment by mohit-dhiman** [comment]
Sure, I'll try to ask this on the opus mailing list.
Thank you for your help.
