### ISSUE TITLE
CAN NOT INSTAL WITH UBUNTU: packge not available

### ISSUE THREAD

**Issue by fukemy** [traud/asterisk-opus#26]
please I need your help, I am new with Ubuntu

<img width="1512" alt="Ảnh màn hình 2024-03-27 lúc 14 18 06" src="https://github.com/traud/asterisk-opus/assets/8202437/b65e25e3-9337-4b49-b5f5-43e9dfa0b1f9">

**Comment by traud** [comment]
From which guide, blog or webpage are you coming from?

With Ubuntu 20.04 LTS (focal), there was a package called ``asterisk-opus``. 
With Ubuntu 22.04 LTS (jammy), that package moved to ``asterisk-modules``.
Therefore, you have to go back to Ubuntu 20.04 LTS. Or you go for ``sudo apt install asterisk-modules``. However, within that package, the module for Opus-Codec is missing, the shared library ``codec_opus_open_source.so``. At least in Ubuntu 22.04 till 23.10. In Ubuntu 24.04 LTS (noble) this library will be present again. Consequently, my recommendation, either go back to Ubuntu 20.04 LTS or wait four weeks and go for Ubuntu 24.04 LTS.

Finally, I do not maintain nor provide that package. That is done by the [Debian VoIP Team](http://lists.alioth.debian.org/pipermail/pkg-voip-maintainers/). If you need further support on this topic, I recommend to ask in their mailing. I am closing this report because it is out of the scope of my project, I only support creating the module yourself.
