### ISSUE TITLE
Master should contain latest commit

### ISSUE THREAD

**Issue by verticelo** [traud/asterisk-opus#5]
Hi,

The documentation points to:
github.com/traud/asterisk-opus/archive/master.tar.gz

However, the master branch has not had a merge from 13.7 hence the install instructions do not work. So I suppose it needs a merge or the docs should be updated to download a different file instead.

Cheers!

**Comment by traud** [comment]
Thank you for the report. That error happened because I copied the Read Me of another project of mine. Therefore, the note was very welcome. When you find other issues (big or small, even typos, grammar or sentences which can be shorted with a better suited verb), please, do not hesitate and create a new issue report.

When it comes to the master branch, I have not made my mind yet whether or how to merge the changes there. As of today, the 13.7 branch is the head of the project (default branch). Backports go into the 13.3 branch, for those users on older distributions.

**Comment by verticelo** [comment]
Great! I will report some more things going forward and try to contribute. We are testing this patch carefully now and we are running a bunch of test scenarios for it and I will let you know the outcome.

We have already discovered a situation where Digium binary fails to transcode and your patch works flawlessly.
