### ISSUE TITLE
Patch from Asterisk: FMTP generation

### ISSUE THREAD

**Issue by verticelo** [traud/asterisk-opus#6]
Hi!

Just saw that the Asterisk team made a patch:

https://code.asterisk.org/code/viewrep/asterisk/res/res_format_attr_opus.c?r1&r2=2c031b67d3c7da83bab914bcdaad45d2a0bc9ff8

Is this patch applicable to this repo as well? Just asking since they seem to be using your code elsewhere.

Notes:
res_format_attr_opus: Fix fmtp generation. 
res_format_attr_opus assumed that the string being passed into it was 
empty. It tried to determine if the only thing it had written was 

a=fmtp:<num> 

And if it had, it would reset the string. Its calculation was off when 
working with chan_sip, though. chan_sip passes the entire built SDP 
rather than an empty string. This resulted in always putting an empty 
fmtp line in the SDP.

**Comment by traud** [comment]
Thank you for the heads-up. Reporting such changes of Asterisk development is always good, because the change might be unknown otherwise. However in this case, this repository here is not affected. The original issue was introduced by Digium when they added support for their binary module. This repository here uses the last version of `res/res_format_attr_opus.c` before that change.
